<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
	    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PublishReadyToRun>false</PublishReadyToRun>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <PublishAot>true</PublishAot>
        <!--
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <IlcGenerateStackTraceInformation>true</IlcGenerateStackTraceInformation>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        -->
    </PropertyGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
        <PackageReference Include="Avalonia" Version="11.3.18" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="MySqlConnector" Version="2.3.6" />
        <PackageReference Include="PublishAotCross.Tools" Version="0.6.0.7" />
        <PackageReference Include="Sdcb.LibYuv.runtime.linux-x64" Version="1.0.0.12" />
        <PackageReference Include="Sdcb.LibYuv.runtime.osx-arm64" Version="1.0.0.12" />
        <PackageReference Include="Sdcb.LibYuv.runtime.win-x64" Version="1.0.0.12" />
        <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    </ItemGroup>

    <!-- ========== Windows x64 原生库 ========== -->
    <ItemGroup Condition="'$(RuntimeIdentifier)'=='win-x64'">
        <Content Include="NativeLib/win-x64/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>

    <!-- ========== Linux‑x64（UOS、麒麟x86_64）原生库 ========== -->
    <ItemGroup Condition="'$(RuntimeIdentifier)'=='linux-x64'">
        <Content Include="NativeLib/linux-x64/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>

    <!-- ========== Linux‑ARM64（飞腾、鲲鹏ARM64）原生库 ========== -->
    <ItemGroup Condition="'$(RuntimeIdentifier)'=='linux-arm64'">
        <Content Include="NativeLib/linux-arm64/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>

    <!-- ========== osx-arm64 虚拟 ========== -->
    <ItemGroup Condition="'$(RuntimeIdentifier)'=='osx-arm64'">
        <Content Include="NativeLib/osx-arm64/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>
    <ItemGroup Condition="'$(RuntimeIdentifier)'=='osx-arm64'">
        <Content Include="libvlc/osx-arm64/lib/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <Link>libvlc/osx-arm64/lib/%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>

        <Content Include="libvlc/osx-arm64/plugins/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <Link>libvlc/osx-arm64/plugins/%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>
</Project>
